apiVersion: apps/v1
kind: Deployment
metadata:
  name: savings-api-deployment-uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: savings-api-uat
  template:
    metadata:
      labels:
        app: savings-api-uat
    spec:
      containers:
        - name: savings-api
          image: savings-api-image-uat
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
