apiVersion: v1
kind: Service
metadata:
  name: savings-api-service-qa
spec:
  selector:
    app: savings-api-qa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
      nodePort: 31682  #This is the fixed port!
  type: NodePort
